{application,webmachine_demo,
             [{description,"webmachine_demo"},
              {vsn,"1"},
              {modules,[webmachine_demo,webmachine_demo_app,
                        webmachine_demo_resource,webmachine_demo_sup]},
              {registered,[]},
              {applications,[kernel,stdlib,inets,crypto,mochiweb,webmachine]},
              {mod,{webmachine_demo_app,[]}},
              {env,[]}]}.
